baseURL: "https://danieliglesias.cl" 
title: Daniel Iglesias
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Personal Projects
          url: personal-projects/
          weight: 2 
        - name: Industry Experience
          url: industry-work/
          weight: 3
        - name: Papers
          url: papers/
          weight: 4
        - name: Blog
          url: https://substack.com/@danieliglesias
          weight: 5 
        - name: Freelance
          url: https://www.upwork.com/freelancers/~01b3e7d16e0acf7c58

          weight: 6

params:
    description: "This website hosts Daniel Iglesias' research papers, projects, contact information, and curriculum vitae"
    author: Daniel Iglesias
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: MSc. Daniel Iglesias
          subtitle: "I am a Researcher in the Universidad de La Frontera, Temuco, Chile. My research focuses on electronic engineering, Internet of Things, Aritificial Intelligence, and FPGAs."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Personal Projects
              url: personal-projects/
            - name: Industry Experience
              url: industry-work/
            - name: Papers
              url: papers/
            - name: Blog
              url: https://substack.com/@danieliglesias
            - name: Freelance
              url: https://www.upwork.com/freelancers/~01b3e7d16e0acf7c58

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:d.iglesias01@ufromail.cl
        - name: Office Hours
          url: https://calendar.app.google/RHcYcoHzz7F2usms7
        - name: Substack
          url: https://substack.com/@danieliglesias
        - name: Reddit
          url: https://www.reddit.com/user/Daniel_Iglesias/
        - name: Twitter
          url: https://x.com/DanielIglesiasQ
        - name: LinkedIn
          url: https://www.linkedin.com/in/d-iglesias/
        - name: GitHub
          url: https://github.com/iglesias-daniel
        - name: UpWork
          url: https://www.upwork.com/freelancers/~01b3e7d16e0acf7c58
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=es&user=-m1mpg8AAAAJ
        - name: ORCiD
          url: https://orcid.org/0009-0005-8455-1727
        - name: ResearchGate
          url: https://www.researchgate.net/profile/Daniel-Iglesias-16
        - name: IEEE
          url: https://ieeexplore.ieee.org/author/37086574630
        - name: Goodreads
          url: https://www.goodreads.com/user/show/40086181-daniel-iglesias
        - name: Steam
          url: https://steamcommunity.com/id/danielOfficialProfile/
        - name: Letterboxd
          url: https://letterboxd.com/daex_/
        - name: Leetcode
          url: https://leetcode.com/u/daniel-iglesias/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Daniel Iglesias"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2